[versions]
java = "20"
springBoot = { strictly = "[3.0.6, 4.0[" }
spockSpring = "2.4-M1-groovy-4.0"

[libraries]
spring-boot = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spockSpring" }

[bundles]


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
